
```{r}
library(tidyverse)
library(cmdstanr)
source("R/simulate.R")
source("R/reshape.R")
set.seed(1)
```

```{r}
N <- 200
K <- 20
X <- matrix(1, nrow = N, ncol = 2)
X[sample(1:N, size = N / 2), 2] <- 0
beta <- matrix(rnorm(2 * K, 0, 3), nrow = K, ncol = 2)
beta[1:4, 2] <- 0
beta <- beta[order(beta[, 2]), ]
std <- 1
y <- lnm_simulator(X, beta, sigma = std)
```

```{r}
# calculate mu for further visualization
mu <- matrix(nrow = N, ncol = K)
for (i in 1:N) {
    mu[i, ] <- rnorm(K, X[i, ] %*% t(beta), std)
}
mu_truth <- mu %>%
  as.data.frame() %>%
  rowid_to_column("sample") %>%
  pivot_longer(!sample, names_to = "Taxon", values_to = "value") %>%
  mutate(type = "truth")
info <- data.frame(sample = 1:N, 
                   trt = X[, 2])
true_para <- data.frame(
  Taxon = str_c("V", 1:K),
  beta1_t = beta[, 2],
  beta1_intercept = beta[, 1],
  type = "truth"
)
```






## LNM
```{r}
model_lnm <- cmdstan_model("stan/lnm.stan")
data_list <- list(N = N,  K = K, trt = X[, 2], y = y)
fit_lnm <- model_lnm$variational(data_list)
```


```{r}
z <- fit_lnm$draws("beta1_t") / fit_lnm$draws("sigmas1")
```

```{r}
hist(z)
```

